apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apis.axp.axonect.com
spec:
  group: axp.axonect.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                swaggerConfigMapName:
                  type: string
          required:
            - spec
  scope: Namespaced
  names:
    plural: apis
    singular: api
    kind: API
status:
  storedVersions:
    - v1